AMZN_ASSOCIATE_TAG:
AWS_ACCESS_KEY:
AWS_SECRET_KEY:
CONTACT_EMAIL: hi@email.com
DEFAULT_EMAIL_SENDER: app@email.com
DEFAULT_CONTACT_EMAIL: contact@email.com
GOOGLE_DRIVE_CLIENT_ID:
GOOGLE_DRIVE_CLIENT_SECRET:
GOOGLE_DRIVE_ACCESS_TOKEN:
GOOGLE_DRIVE_REFRESH_TOKEN:
GOOGLE_DRIVE_PUBLIC_FOLDER_ID:
